### ISSUE TITLE
miktex-makepk did not succeed.

### ISSUE THREAD

**Issue by jorgecastillo2** [jankapunkt/latexcv#32] opened 2020-07-20 22:18 UTC
When I compile, change credentials, etc, I get the following error message:

**Sorry, but miktex-makepk did not succeed. The log file hopefully contains the information to get MiKTeX going again: C:\Users\aleph\AppData\Local\MiKTeX\2.9\miktex\log\miktex-makepk.log**

the log file contains:

**2020-07-20 18:10:34,490-0400 INFO  miktex-makepk - starting with command line: miktex-makepk --enable-installer --verbose Raleway-Bold-tlf-t1--base 600 600 magstep(0.0)
2020-07-20 18:10:34,492-0400 INFO  makepk - Trying to make PK font Raleway-Bold-tlf-t1--base at 600 DPI...
2020-07-20 18:10:34,507-0400 INFO  makepk - The METFAONT mode is: ljfour
2020-07-20 18:10:34,520-0400 INFO  makepk - Running miktex-makemf.exe...
2020-07-20 18:10:34,520-0400 INFO  makepk - running: miktex-makemf.exe --miktex-enable-installer --miktex-disable-maintenance --verbose Raleway-Bold-tlf-t1--base
2020-07-20 18:10:35,127-0400 INFO  makepk - Running miktex-ttf2pk.exe...
2020-07-20 18:10:35,128-0400 INFO  makepk - running: miktex-ttf2pk.exe --miktex-enable-installer --miktex-disable-maintenance -q -t Raleway-Bold-tlf-t1--base
2020-07-20 18:10:54,853-0400 FATAL miktex-makepk - The process terminated due to an access violation.
2020-07-20 18:10:54,854-0400 FATAL miktex-makepk - Info: fileName="C:\Program Files\MiKTeX 2.9\miktex/bin/x64\miktex-ttf2pk.exe"
2020-07-20 18:10:54,854-0400 FATAL miktex-makepk - Source: Libraries\MiKTeX\Core\Process\win\winProcess.cpp
2020-07-20 18:10:54,854-0400 FATAL miktex-makepk - Line: 474
2020-07-20 18:10:58,983-0400 INFO  miktex-makepk - starting with command line: miktex-makepk --enable-installer --verbose Raleway-Bold-tlf-t1--base 600 600 magstep(0.0)
2020-07-20 18:10:58,985-0400 INFO  makepk - Trying to make PK font Raleway-Bold-tlf-t1--base at 600 DPI...
2020-07-20 18:10:58,991-0400 INFO  makepk - The METFAONT mode is: ljfour
2020-07-20 18:10:59,000-0400 INFO  makepk - Running miktex-makemf.exe...
2020-07-20 18:10:59,000-0400 INFO  makepk - running: miktex-makemf.exe --miktex-enable-installer --miktex-disable-maintenance --verbose Raleway-Bold-tlf-t1--base
2020-07-20 18:10:59,299-0400 INFO  makepk - Running miktex-ttf2pk.exe...
2020-07-20 18:10:59,299-0400 INFO  makepk - running: miktex-ttf2pk.exe --miktex-enable-installer --miktex-disable-maintenance -q -t Raleway-Bold-tlf-t1--base
2020-07-20 18:10:59,719-0400 FATAL miktex-makepk - PK font Raleway-Bold-tlf-t1--base could not be created.
2020-07-20 18:10:59,719-0400 FATAL miktex-makepk - PK font Raleway-Bold-tlf-t1--base could not be created.
2020-07-20 18:10:59,719-0400 FATAL miktex-makepk - Info: 
2020-07-20 18:10:59,719-0400 FATAL miktex-makepk - Source: 
2020-07-20 18:10:59,719-0400 FATAL miktex-makepk - Line: 0**

**Comment by jankapunkt** [comment] 2020-07-21 06:56
Read the message carefully there is a part ` Terminate process due to access violation`. I am no Windows pro so maybe someone can put a light on this?

**Comment by jankapunkt** [comment] 2020-08-31 12:29
Hey  @jorgecastillo2 did you resolve the issue? If so, please close it, otherwise please add more information for reproduction so we can find a solution.

**Comment by jankapunkt** [comment] 2021-04-13 06:11
@jorgecastillo2 I am closing this question due to silence. Feel free to reopen if this issue persists or you think it should be reopened

**Closed** 2021-04-13 06:13 UTC
Labels: question
